### ISSUE TITLE
Hitting 404 after log in

### ISSUE THREAD

**Issue by harismahmood89** [kitajchuk/node-squarespace-server#101]
I can't seem to figure out why I keep hitting a 404 after logging in to the local site. Is there a particular URL I'm supposed to be hitting past the `localhost:5050` part?

Any help would be appreciated! Thanks

**Comment by harismahmood89** [comment]
Sorry to be a pain, but any ideas? @kitajchuk?

**Comment by kitajchuk** [comment]
Can you give me any more information about your setup? There isn't a particular url you need to hit. The server acts as a proxy to your remote Squarespace site. What template are you using?

**Comment by harismahmood89** [comment]
I'm using the default base developer template. 

I added the `siteurl` and `sandbox` option in the template file. see below:
```
{
  "name" : "Base Template",
  "author" : "Squarespace",

  "server": {
    "siteurl": "https://haris-mahmood-ui3k.squarespace.com",
    "sandbox": true
  },
  
  "layouts" : {
    "default" : {
      "name" : "Default",
      "regions" : [ "site" ]
    }
  },
  
  "navigations" : [ {
      "title" : "Main Navigation",
      "name" : "mainNav"
  } ],

  "stylesheets" : [ "base.less" ],

  "systemCollections" : [ "products" ]
}
```
I run the server as directed. It presents the login screen, but after signing in it just throws a 404 error.

**Comment by kitajchuk** [comment]
Do you have an active sitewide password?

**Comment by harismahmood89** [comment]
Nope - i tried testing it out by putting in my squarespace password, but that lead to the same results.

**Comment by harismahmood89** [comment]
Would someone have a repository on github with their set up? Maybe I can give that a shot or compare it to what I have myself?

Really want to get this working.

**Comment by kitajchuk** [comment]
This is super hard to troubleshoot from my end. The node server just acts as a proxy, replicating as much of Squarespace as it can. Super particular issues like this are hard to debug from behind a wall with no visibility into your setup. I know sandbox mode sites are particular in general. I'm wondering if something changed there that is causing the issue...

**Comment by blaisefreeman** [comment]
I'm having the same problem. Using a squarespace site in trial/sandbox developer mode. Can enter my username/password but then takes me directly to a 404 screen. 

To get started I just followed this guide step-by-step: https://www.youtube.com/watch?v=tl6Dr4wh0ls

**Comment by blaisefreeman** [comment]
Tried it with a **paid** site, not trial/sandboxed, and it worked fine. 

So the problem appears to be with sandboxed sites...

**Comment by harismahmood89** [comment]
Thanks for the find. Unfortunate that sandbox/trial doesn't work anymore. Wonder what squarespace changed on their end to cause it to break.

**Comment by kitajchuk** [comment]
This isn't too surprising. Sandbox sites are protected anyway. It was probably a fluke that the header spoofing worked for the node server to get around that. But I'm guessing @harismahmood89 is right and something has changed that stops this from working anymore.

**Comment by justincharles** [comment]
I've got a paid site but I'm still getting hit with a 404.

**Comment by kitajchuk** [comment]
@justincharles - Which template are you using?

**Comment by justincharles** [comment]
Base Template

**Comment by kitajchuk** [comment]
Password, no password?

**Comment by justincharles** [comment]
No password

**Comment by kitajchuk** [comment]
Hmm. Anything else of mention, or just the 404?

**Comment by justincharles** [comment]
No, just the 404.

**Comment by kitajchuk** [comment]
I have a trial account using base and it works alright locally. But I haven't updated a lot with it. What is your setup like? Pages, config, styles etc?

**Comment by justincharles** [comment]
I'm just setting things up fresh to start development on a new site so it's basically just grunt-init-squarespace.

**Comment by kitajchuk** [comment]
What does your template.conf file look like?

**Comment by justincharles** [comment]
`{
  "name" : "Base Template",
  "author" : "Squarespace",

  "layouts" : {
    "default" : {
      "name" : "Default",
      "regions" : [ "site" ]
    }
  },

  "navigations" : [ {
      "title" : "Main Navigation",
      "name" : "mainNav"
  } ],

  "stylesheets" : [ "screen.css" ],

  "systemCollections" : [ "products" ],

  "server": {
      "siteurl" : "https://eacypaanyc.squarespace.com"
  }
}`

**Comment by kitajchuk** [comment]
Bizarre. Did you bust your cache and restart the server?

**Comment by justincharles** [comment]
Yup : (

**Comment by justincharles** [comment]
It works now. Probably something weird on Squarespace's end.

**Comment by kitajchuk** [comment]
Really, dang... I've had weird issues with Squarespace in regards to them stopping a site of mine under the pretenses of "too many unknown requests" before. Glad its working now.

**Comment by bcackerman** [comment]
If I have a sitewide password, what would the solve be?

**Comment by bcackerman** [comment]
I actually just removed the sitewide password AND set a page to be the Homepage and the 404 error was gone.

**Comment by kitajchuk** [comment]
Sitewide passwords are fine, you just have to define them in the `server` config in your template.conf file. https://github.com/kitajchuk/node-squarespace-server#usage

**Comment by shamroze** [comment]
So is it a no? for trial mode for this good service kitajchuk ? :( As im unable to pass through the 404 issue and my web is on trial mode...

**Comment by kitajchuk** [comment]
@shamroze - I don't think so. I have been running sites in trial mode with no issues. I'm not positive what is causing the 404 for you, but I can ask a few questions here that may help.

1. Are you using the absolute latest version of the server? `sqs --version` will tell you which version you are on. 0.3.5 is the [latest on npm](https://www.npmjs.com/package/node-squarespace-server). If you're not up to date, `npm update -g node-squarespace-server` will do it. Due to the nature of what this project is attempting to achieve, its actually recommended to always use the latest :)
2. As long as you are up to date with the server, have you busted your local cache and tried again? `sqs buster` will do this for you.
3. Beyond the items above, what collection type is your homepage set to? For instance, `page`, `index`, `folder`, `blog` etc... Obviously this includes any custom collection types you have created, though those all just follow a standard collection type format anyway.
4. Can you access any pages locally? Beyond the 404 on your homepage, can you directly hit any other page?
5. Also, which template are you using? Or which one did you start from? I typically start with the blank `base-template`.

I know I'm asking a lot of questions but its definitely difficult to debug what causes issues for you guys sometimes without being able to run your site myself and debug on the fly. Let me know about this list of questions and we can go from there.

**Comment by shamroze** [comment]
@kitajchuk Im super glad to see your reply!! and thanks a ton for trying to debug  with such care. However I'm at home and my internet connection is not working very well.I'll have to re set it up as i messed quite a lot of stuff. But i'll be responding u as soon as i get to my table. I'll re check and re do all the things u mentioned above and will update you by next 12 hours i suppose. You can reply whenever its cool to you :) Thanks again for the reply!

**Comment by kitajchuk** [comment]
@shamroze no worries :)

**Comment by shamroze** [comment]
@kitajchuk hey i followed what u asked to and now i can see my demo homepage up and running!! Previously i had an older version.
I did sqs buster
and it was a base template as well.
However when i hit 'sqs server' it throws this error.

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EADDRINUSE

but then when i do sqs server --port=8000 and do localhost:8000/home on my browser it opens up fine :)
Thanks!!!

**Comment by kitajchuk** [comment]
That error is due to having something else already running on port 5050, which is the default for the node server. So it makes sense that running the server on another port worked for you. Check your running node processes and make sure you don't have an instance of the server running in the background blocking your ability to run the default port 5050 :D

Glad you're up and running!

**Comment by shamroze** [comment]
(Y) :+1:

**Comment by shamroze** [comment]
:+1:
