### ISSUE TITLE
watch ENOENT error

### ISSUE THREAD

**Issue by alleyhector** [kitajchuk/node-squarespace-server#115]
I get this error when trying to run the server. Any ideas what is going on?

> sqs-server: Error compiling mobile.less: 'sqs-grid-breaker.less' wasn't found
> sqs-server: Error compiling index.less: 'sqs-ui-font.less' wasn't found
> sqs-server: Error compiling blog.less: .border-box is undefined
> sqs-server: Error compiling base.less: .transform is undefined
> sqs-server: Error compiling mixins.less: 'sqs-ui-font.less' wasn't found
fs.js:1172
    throw errnoException(err, 'watch');
          ^
Error: watch ENOENT
    at exports._errnoException (util.js:746:11)
    at FSWatcher.start (fs.js:1172:11)
    at Object.fs.watch (fs.js:1198:11)
    at Object.watch (/usr/local/lib/node_modules/node-squarespace-server/squarespace-template.js:151:8)
    at /usr/local/lib/node_modules/node-squarespace-server/squarespace-server.js:592:33
    at done (/usr/local/lib/node_modules/node-squarespace-server/squarespace-template.js:106:13)
    at read (/usr/local/lib/node_modules/node-squarespace-server/squarespace-template.js:757:13)
    at /usr/local/lib/node_modules/node-squarespace-server/squarespace-template.js:782:29
    at /usr/local/lib/node_modules/node-squarespace-server/squarespace-util.js:85:17
    at fs.js:334:14

**Comment by blakeswitchco** [comment]
The problem derives from a missing 'pages' directory. If you create that directory in the root of the project, it should work.

**Comment by kitajchuk** [comment]
Hmm. The `sqs-server` logs are correct and due to the fact that the magic sqs imports don't work locally, obviously. The watch error is no good, though. I just added support for static pages and obviously never tested with the absence of a `pages` directory. This should be resolved, though, so you should not be required to make a pages directory if you aren't using static pages. But for now you can add a pages directory to keep moving.
