### ISSUE TITLE
The "Local LESS" Issue

### ISSUE THREAD

**Issue by cwaring** [kitajchuk/node-squarespace-server#79]
I'm currently working with the Bedford template as a base and Squarespace provides a couple of custom import shortcuts that must get expanded at runtime using their LESS compiler. These are causing silent errors locally during compilation because they cannot be resolved.
```LESS
@import 'sqs-ui-font';
@import 'sqs-grid-breaker';
```

![screen shot 2015-02-11 at 22 50 08](https://cloud.githubusercontent.com/assets/106938/6157307/9a986dcc-b240-11e4-93a4-ef14487f9f8f.png)

What might be the best way to work around this? I guess it's not possible to include these dynamically so maybe a fallback could be escaping them pre compilation but that could cause other issues with missing mixins and variables.

Related #57 also needs to be fixed to keep the variable context too, I'll have a stab at solving it if anyone has an idea how best to handle this issue.

Keen to hear your ideas @kitajchuk.

**Comment by kitajchuk** [comment]
Yes, this one is on my radar. I can take a look at it again and see what I come up with. I have been planning on circling back to this issue as I know its a pain point for people. I'll let you know what I find / when its resolved :)

**Comment by kitajchuk** [comment]
The styles from those imports are loaded locally from the remote site.

The current setup is that the remote site.css loads and then the local one is loaded on top of that. There's no good way to do this right now, so that is the setup for the time being.

I think the only real issue with these imports is that any variables defined in them and then used in your local less files would be undefined.

If it weren't for the variables issue, these could just be ignored in the local less compilation and the fallback would be for the remote styles from these imports to be displayed.

That may be an initial resolve to get rid of the undefined output in the local css. But accounting for remote variable declarations wouldn't be possible...

... thinking out load...

**Comment by kitajchuk** [comment]
@foleyatwork - Any insights on this?

**Comment by cwaring** [comment]
Good to hear it's on the radar, I'm happy to chip in where possible.
The main issue at the moment seems to be that the Node LESS compiler exits when it hits an error, so the output is truncated and replaced with `undefined `.
If it was possible to emulate these includes locally, (maybe @foleyatwork could provided the source?), then we could regex out the squarespace site.css from the headers and just depend on the local one.
Downside: doing this would mean any style editor tweaks would be lost, unless there was a way to include just the tweaks as a separate css somehow.

**Comment by kitajchuk** [comment]
Yeah. I think for starters it should capture the less compiler errors and keep from outputting the "undefined" strings in the local css.

As for remote site.css, I would love to parse that out from the headers and run only the local styles. The only issue currently is that there is a bunch of Squarespace commons css that is a part of that which we also don't have locally. I tried this at one point and you need that commons css, unfortunately.

What you get is Squarespace css compiled on top of your site.css. It would be doable to remove the remote site.css if it didn't have the extra stuff you need compiled on top of it. Since the commerce stylesheet is a separate request, that css could be as well... but that's a change for Squarespace to make.

The only thing I could think of with the current limitations would be to mark your styles with a leading comment, something like "/*! Developer Styles */" so they could be parsed out. Unfortunately this relies on developers adding that comment to the top of their first stylesheet. As long as its documented in the readme, its a viable option for the time being I suppose.

**Comment by cwaring** [comment]
I like the preserved comment idea, that provides a sensible start to separating the two.

**Comment by kitajchuk** [comment]
I'll see about getting that in there as a starting point :)

**Comment by kitajchuk** [comment]
Moving this into an issue space where the focus is just for the LESS compiling: https://github.com/kitajchuk/node-squarespace-server/issues/94

**Comment by cwaring** [comment]
:+1:
