### ISSUE TITLE
HTML Entities not rendered as they are on SquareSpace.

### ISSUE THREAD

**Issue by loadedsith** [kitajchuk/node-squarespace-server#85]
This is a minor issue at best.

I've a Copyright HTML entity "©" in my footer. It renders on SquareSpace and their editor, but not on my node-squarespace-server version.

No need to fix it on my behalf. Just wanted to let you know.

**Comment by kitajchuk** [comment]
Weird. I'll still look into this :)

**Comment by kitajchuk** [comment]
Yep, looks like it is because those characters are coming back as "\uFFFD", the unicode replacement character for unknown character values. Since it works on Squarespace, it must be due to the fact that I am using the request module to retrieve all the block widget content.

Also, Squarespace actually renders those as "©" rather than "&copy;" which is unfortunate.
