### ISSUE TITLE
LESS Changes don't seem to affect anything

### ISSUE THREAD

**Issue by hhff** [kitajchuk/node-squarespace-server#98]
Hi @kitajchuk !

Loving this library!  Just starting to get up and going - and a little confused re: LESS workflow.  I'm making changes to base.less, and the server sees the changes and reloads the Template, however the changes aren't reflected.

```
> sqs-server: Server.port: 5050
> sqs-middleware: BLOCK ERROR - Empty block JSON
> sqs-server: Server.error: Empty block JSON
> sqs-server: Template.watch: 4913 updated
> sqs-server: Template.watch: base.less~ updated
> sqs-server: Template.watch: base.less updated
> sqs-server: Template.reloaded
```

The compiled `/site.css` only contains the `reset.css` file -  not the contents of `base.less`.

I'm using the Squarespace base template: https://github.com/Squarespace/base-template

Happy to edit & PR the README once I know what's going on!

**Comment by kitajchuk** [comment]
Are you importing any of the auto-magical Squarespace LESS files, such as "sqs-grid-breaker"? If that's the case, I'm afraid you're looking at this problem here: https://github.com/kitajchuk/node-squarespace-server/issues/94. Being an open-source project working against a proprietary platform, this issue enters the realm of where what we are capable of really breaks down a bit.

**Comment by hhff** [comment]
Nope - just using the standard Base Template above.  It declares `base.less` in the `template.conf` file, but it definitely isn't included in `/site.css`.

I've been making my edits directly at the bottom of `reset.css`, and those changes are working fine.

**Comment by okalex** [comment]
@hhff, I was having the same problem, but turns out that base template does use some of the "auto-magical" LESS files referred to above. To work around it, open your `base.less` file and comment out the lines that include `@import 'sqs-grid-breaker';` and `padding-left: @site-title-font-letter-spacing;`

@kitajchuk, in order to figure this out, I had to clone the project and add some debugging logs to the compilation step. Perhaps some indication that compilation failed and a description of the problem would be helpful?
